baseURL = "https://yuuk.io/en/blog"
languageCode = "en-us"
title = "<yuuk1>"
theme = "er"
publishDir = "public/en/blog"

[taxonomies]
  category = "categories"
  tag = "tags"
[permalinks]
  posts = "/:year/:filename/"
